
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const classifications = [
    { code: 'C10', description: 'BODY CARE', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'C20', description: 'ORAL CARE', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'C30', description: 'SURFACE CARE', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'C40', description: 'FABRIC CARE', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'G11', description: 'TOILET SOAPS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G12', description: 'SHAMPOOS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G13', description: 'UNDER ARMS PROTECTION', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G14', description: 'CONDITIONER', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G45', description: 'OTHER BODY CARE', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G21', description: 'Dental Creams', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G22', description: 'Toothbrushes', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G23', description: 'Dental Floss', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G24', description: 'Mouth Wash', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G25', description: 'Profesional Products', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G31', description: 'BLEACH', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G32', description: 'LIQUID CLEANER', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G33', description: 'DISH WASHERS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G41', description: 'DETERGENTS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G42', description: 'LAUNDRY BARS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G43', description: 'OPTICAL BRIGTENERS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G44', description: 'FABRIC SOFTENERS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G47', description: 'SYNDET BARS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'B03', description: 'LAVADOR MANZANA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'B14', description: 'PALMOLIVE KIDS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M01', description: 'Palmolive', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M03', description: 'Protex', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M43', description: 'Irish Spring', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M50', description: 'Lavador Miel', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M66', description: 'Lavador Almendra', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M70', description: 'LAVADOR MELON', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M71', description: 'AROMA TERAPIA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M73', description: 'LAVADOR MIEL LIQUIDO', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M74', description: 'PALMOLIVE BOTANICALS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M75', description: 'SHOWER GEL BOTANICALS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M79', description: 'PEPINO Y LECHE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M04', description: 'Optims', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M44', description: 'Palmolive', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M77', description: 'Palmolive POS BOTANICALS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M78', description: 'Palmolive ACOND.  BOTANICALS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M33', description: 'Men Speed Stick', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M35', description: 'Lady Speed Stick', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M64', description: 'Speed Stick Gel', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M65', description: 'Lady Speed Stick Gel', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M76', description: 'LSS ULTRA DRY CREAM', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M90', description: 'SPEED STICK CLEAR AP', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M95', description: 'LADY SPEED ST. ROLL ON', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M96', description: 'SPEED STICK  ROLL ON', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M32', description: 'Protex Liquido', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M46', description: 'Lavador Liquido', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M05', description: 'Colgate Menta', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M06', description: 'Colgate Total', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M07', description: 'Tartar Control', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M08', description: 'Backing Soda', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M28', description: 'COLGATE SENSITIVE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M30', description: 'Colgate Junior', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M34', description: 'Colgate Gel', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M54', description: 'CDC Dloble Frescura', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M56', description: 'CDC Whitening', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M68', description: 'CDC Frescura Confiable', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M87', description: 'CDC TRIPLE ACCION', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M88', description: 'CDC Herbal', groupNumber: 3, groupType: 'BRAND' },
    { code: 'B05', description: 'COLGATE ACTIVE FLEXIBLE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'B15', description: 'COLGATE MOTION', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M09', description: 'Colgate Plus', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M10', description: 'Colgate Classisc', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M11', description: 'Precision', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M51', description: 'CEP REPLACE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M52', description: 'Cep. Classic Deluxe', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M57', description: 'Cep. Wave Sensation', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M61', description: 'Colgate Navigator', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M62', description: 'KIDS GRP`EMS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M81', description: 'CEP ANGLE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M82', description: 'CEP EXTRA CLEAN', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M92', description: 'COLGATE ACTIBRUSH', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M93', description: 'COLGATE ACTIBRUSH REFILL', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M94', description: 'CEP PREM. ULTRA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M12', description: 'Hilo Dental', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M53', description: 'Colgate Plax', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M13', description: 'Productos Profesionales', groupNumber: 3, groupType: 'BRAND' },
    { code: 'CG', description: 'GENERICOS', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'SC12', description: '3M COLMADO', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC13', description: '3M - SUPERMERCADO', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'M3M', description: '3M DOMINICANA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'SC01', description: 'PROTECTORES - J&J', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC02', description: 'TOALLAS - J&j', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC03', description: 'BARRAS - CHOC', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC04', description: 'FUN-SIZE', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC05', description: '8 PACK', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC06', description: 'MINIATURAS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC07', description: 'SKITTLES', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC08', description: 'STABURTS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC09', description: 'M & M', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC10', description: 'PEG PAP', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC11', description: 'WHISKAS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC14', description: 'PEDIGREE', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC15', description: 'MEDICINA  - BAYER', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC16', description: 'PAÑALES DESECHABLE', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC17', description: 'DIXX CLORO', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC18', description: 'DINAFA - MEDICINA', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC19', description: 'SCHICK - CAOBO', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'SC20', description: 'POSTALES - ALBUM', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'MTOA', description: 'J&J - STAY FREE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MTOB', description: 'J&J - CARE-FREE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MGEN', description: 'SCHICK EXACTA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MDIN', description: 'DINAFA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MBAY', description: 'BAYER DOMINICANA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MDIX', description: 'CLORO DIXX', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MPN', description: 'PAÑALES ANGELIN', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MBAR', description: 'MARS  FOOD - CHOCOLATES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MPOS', description: 'POSTALES - AVES DE MIS PAIS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'CA', description: 'ALIMENTOS PARA MASCOTA', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'MPG', description: 'PEDIGREE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MWH', description: 'WHISKAS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MST', description: 'STARBURST', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MSK', description: 'SKITTLES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MFZ', description: 'FUN-SIZE', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MPP', description: 'PEG PACK', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M8P', description: '8-PACK', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MMI', description: 'MINIATURA CHOC', groupNumber: 3, groupType: 'BRAND' },
    { code: 'COL', description: 'COLGATE', groupNumber: 4, groupType: 'OTHER' },
    { code: 'GND', description: 'GRUPO NACIONAL DE DISTRIBUCION', groupNumber: 4, groupType: 'OTHER' },
    { code: 'D01', description: 'SUAVITEL SATCHET', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D02', description: 'CEPILLO PREMIER', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D03', description: 'CEPILLO CLASSIC', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D04', description: 'AXION BOLA', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D05', description: 'FAB TOTAL', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D06', description: 'LSS ROLL-ON', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D07', description: 'MSS ROLL-ON', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D08', description: 'PROTEX', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D09', description: 'FAB TOTAL 200 GRS.', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D10', description: 'PLAX', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D11', description: 'SUAVITEL SIN SATCHET', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D12', description: 'LSS BARRA', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D13', description: 'MSS BARRA', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D14', description: 'CEPILLOS (360 Y ZZ)', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D15', description: 'PALMOLIVE', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D16', description: 'CDC TOTAL 12', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D17', description: 'FAB TOTAL 400 GRS.', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D18', description: 'FAB TOTAL 100 GRS.', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D19', description: 'AXION LIQUIDO', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D20', description: 'FAB TOTAL', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D21', description: 'FABULOSO', groupNumber: 5, groupType: 'OTHER' },
    { code: 'OFER', description: 'OFERTA', groupNumber: 6, groupType: 'OTHER' },
    { code: 'OFF', description: 'OFERTA DE COLGATE', groupNumber: 6, groupType: 'OTHER' },
    { code: 'M97', description: 'ULTREX', groupNumber: 3, groupType: 'BRAND' },
    { code: 'G48', description: 'DETERGENTE(OTRO)', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'C15', description: 'CUIDADO DE TELAS', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'REG', description: 'REGULAR', groupNumber: 6, groupType: 'OTHER' },
    { code: 'G49', description: 'Shower Gel', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'G50', description: 'Hand Soap', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'M14', description: 'Ajax Cloro', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M41', description: 'Cloro Blanco', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M49', description: 'Ajax Floral', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M83', description: 'CLORO MANZANA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M15', description: 'Fabuloso', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M16', description: 'Ajax Casa', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M42', description: 'Desinfectante Prosol', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M63', description: 'AJAX LIMPIADOR LIQUIDO', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M67', description: 'Ajax Fiestas de Flores', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M89', description: 'AJAX ANTIBACTERIAL', groupNumber: 3, groupType: 'BRAND' },
    { code: 'B01', description: 'AXION SENSACION PRIMAVERAL', groupNumber: 3, groupType: 'BRAND' },
    { code: 'B02', description: 'AXION PASTA MANZANA', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M17', description: 'Axion Crema', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M18', description: 'Axion Liquido', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M31', description: 'Axion Solido', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M38', description: 'Caracol', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M45', description: 'Alto Poder', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M59', description: 'Axion Crema Antibacterial', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M19', description: 'Fab Total', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M20', description: 'Fab Matic', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M21', description: 'Fab Ultra', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M22', description: 'Fab con Blanqueador', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M23', description: 'Fuerza Fr¡a', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M39', description: 'Alto Poder', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M40', description: 'Ese', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M47', description: 'Blanko', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M24', description: 'Octagon', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M25', description: 'Viva', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M37', description: 'Lavador', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M26', description: 'Rayito', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M27', description: 'Suavitel', groupNumber: 3, groupType: 'BRAND' },
    { code: 'M36', description: 'Fab Syndet', groupNumber: 3, groupType: 'BRAND' },
    { code: '1', description: 'PEDIGREE', groupNumber: 3, groupType: 'BRAND' },
    { code: '101', description: 'FREGADOR 3M', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '102', description: 'PEGAMENTOS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '2', description: '3M', groupNumber: 3, groupType: 'BRAND' },
    { code: '201', description: 'ELEVEX', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '3', description: 'TABLETAS', groupNumber: 3, groupType: 'BRAND' },
    { code: '303', description: 'BARRA - CHOCOLATES', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '304', description: 'ALIMENTO PARA MASCOTAS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '03FZ1', description: 'FUN SIZE', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '03MI1', description: 'MINIATURES', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '03PK1', description: '8-PAK', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '03PPK', description: 'PEG PACKS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '03SK1', description: 'SKITTLES', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '03ST1', description: 'STARBURST', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '4', description: 'JOHNSON & JOHNSON', groupNumber: 1, groupType: 'CATEGORY' },
    { code: '404', description: 'TOALLA S. - STAY FREE', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '405', description: 'CARE FREE - PROTECTORES', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '5', description: 'BAYERS', groupNumber: 3, groupType: 'BRAND' },
    { code: '505', description: 'PASTILLAS', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '6', description: 'INVERSIONES CAOBO', groupNumber: 1, groupType: 'CATEGORY' },
    { code: '606', description: 'SCHICK', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '7', description: 'DINAFA', groupNumber: 1, groupType: 'CATEGORY' },
    { code: '701', description: 'MEDICINA', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '8', description: 'DIXX CLORO', groupNumber: 1, groupType: 'CATEGORY' },
    { code: '801', description: 'CLORO', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '9', description: 'PAÑALES', groupNumber: 1, groupType: 'CATEGORY' },
    { code: '901', description: 'PAÑALES ANG', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: '3M', description: '3M', groupNumber: 3, groupType: 'BRAND' },
    { code: '8PK', description: '8-PACK - CHOCOLATES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'CFZ', description: 'FUN SIZE - CHOCOLATES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'CM1', description: 'MINIATURES - CHOCOLATES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'CSK', description: 'SKITTLES - CHOCOLATES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'CST', description: 'STARBURST - CHOCOLATES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'DIX', description: 'CLORO DIXX', groupNumber: 3, groupType: 'BRAND' },
    { code: 'GEN', description: 'RASURADORAS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'MAS', description: 'MASTER FOOD', groupNumber: 3, groupType: 'BRAND' },
    { code: 'P01', description: 'AVES DE MI PAIS', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'P02', description: 'AVES', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'P03', description: 'PROMOCION AVES DE MI PAIS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'PAS', description: 'PASTILLAS', groupNumber: 3, groupType: 'BRAND' },
    { code: 'PEG', description: 'PEG PAKCS - CHOCOLATES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'PNA', description: 'PAÑALES ANGELIN', groupNumber: 3, groupType: 'BRAND' },
    { code: 'TOA', description: 'STAY FREE - JOHNSON', groupNumber: 3, groupType: 'BRAND' },
    { code: 'TOB', description: 'CARE FREE - JOHNSON', groupNumber: 3, groupType: 'BRAND' },
    { code: '3M01', description: '3M DOMINICANA', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'FZ1', description: 'FUN SIZE', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'MA3', description: 'CHOCOLATES', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'CM', description: 'MEDICINA', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'CC', description: 'CHOCOLATES', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'CL', description: 'LIMPIEZAS - CUIDADO HOGAR', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'CP', description: 'HIGIENE PERSONAL', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'T01', description: '1.9LT', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T02', description: '100G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T03', description: '100ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T04', description: '110G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T05', description: '125ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T06', description: '170ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T07', description: '18G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T08', description: '1GAL', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T09', description: '1L', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T10', description: '200ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T11', description: '221ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T12', description: '22ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T13', description: '235GR', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T14', description: '250ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T15', description: '25M', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T16', description: '280ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T17', description: '2LT', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T18', description: '2MM', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T19', description: '2PK', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T20', description: '3LT', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T21', description: '3PK', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T22', description: '400ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T23', description: '40ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T24', description: '425GR', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T25', description: '450ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T26', description: '45G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T27', description: '45ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T28', description: '485ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T29', description: '4PK', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T30', description: '500ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T31', description: '50G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T32', description: '50GR', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T33', description: '50ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T34', description: '60ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T35', description: '63ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T36', description: '65G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T37', description: '70G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T38', description: '750ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T39', description: '75ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T40', description: '850ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T41', description: '85G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T42', description: '85ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T43', description: '900ML', groupNumber: 4, groupType: 'OTHER' },
    { code: 'T44', description: '90G', groupNumber: 4, groupType: 'OTHER' },
    { code: 'D23', description: 'SUAVITEL PREPACK SACHET', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D24', description: 'AXION CREMA', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D25', description: 'BONO', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D26', description: 'FABULOSO 200ML', groupNumber: 5, groupType: 'OTHER' },
    { code: 'CB', description: 'COMBO', groupNumber: 6, groupType: 'OTHER' },
    { code: 'CP1', description: 'PROMOCIONES', groupNumber: 1, groupType: 'CATEGORY' },
    { code: 'GP1', description: 'PROMOCIONES', groupNumber: 2, groupType: 'SUBCATEGORY' },
    { code: 'MP1', description: 'PROMOCIONES', groupNumber: 3, groupType: 'BRAND' },
    { code: 'D22', description: 'FABULOSO SIN SACHET', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D27', description: 'PROMOCIONES', groupNumber: 5, groupType: 'OTHER' },
    { code: 'D28', description: 'RPSM', groupNumber: 5, groupType: 'OTHER' },
];

async function main() {
    const company = await prisma.company.findFirst();
    if (!company) {
        console.error('No company found');
        return;
    }

    console.log(`Seed started for company: ${company.name} (${company.id})`);

    for (const item of classifications) {
        await prisma.itemClassification.upsert({
            where: {
                companyId_code: {
                    companyId: company.id,
                    code: item.code,
                },
            },
            update: {
                description: item.description,
                groupNumber: item.groupNumber,
                groupType: item.groupType as any,
                isActive: true,
            },
            create: {
                companyId: company.id,
                code: item.code,
                description: item.description,
                groupNumber: item.groupNumber,
                groupType: item.groupType as any,
            },
        });
    }

    console.log('Seed finished successfully');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
